substitutions:
  _ENV: PROD

steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      echo "Deploying to environment: ${_ENV}"

options:
  logging: CLOUD_LOGGING_ONLY
