substitutions:
  _REGION: us-central1
  _REPO: my-docker-repo
  _IMAGE: demo-image

steps:
# Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
    - .

# Push Docker image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA



options:
  logging: CLOUD_LOGGING_ONLY
